USE student_attendance;
-- Demo hashes are bcrypt hashes for the demo passwords documented in README.
INSERT IGNORE INTO users(username,password_hash,role,full_name,email) VALUES
('student1','$2a$12$2b2b2b2b2b2b2b2b2b2b2eQ5m2gJ9oV0r3lZrQWmJ4z8Jv8d5u','student','Demo Student','student@example.com'),
('staff1','$2a$12$2b2b2b2b2b2b2b2b2b2b2eQ5m2gJ9oV0r3lZrQWmJ4z8Jv8d5u','staff','Demo Staff','staff@example.com'),
('admin1','$2a$12$2b2b2b2b2b2b2b2b2b2b2eQ5m2gJ9oV0r3lZrQWmJ4z8Jv8d5u','admin','System Administrator','admin@example.com');

-- IMPORTANT: Replace demo password hashes with real bcrypt hashes generated by the application
-- before using these accounts. The seed inserts the users only; use the Admin creation form
-- for secure accounts after initial setup.

INSERT IGNORE INTO students(user_id,student_code) SELECT id,'STU0001' FROM users WHERE username='student1';
INSERT IGNORE INTO staff(user_id,staff_code) SELECT id,'STA0001' FROM users WHERE username='staff1';
INSERT IGNORE INTO courses(course_code,course_name,staff_id) SELECT 'CS101','Computer Science Fundamentals',id FROM staff WHERE staff_code='STA0001';
INSERT IGNORE INTO enrollments(student_id,course_id) SELECT s.id,c.id FROM students s JOIN courses c ON c.course_code='CS101' WHERE s.student_code='STU0001';